const SHOW_CORRESPONDENCE = 'SHOW_CORRESPONDENCE';
const HIDE_CORRESPONDENCE = 'HIDE_CORRESPONDENCE';
const SHOW_TASK = 'SHOW_TASK';
const HIDE_TASK = 'HIDE_TASK';

export default {
    SHOW_CORRESPONDENCE,
    HIDE_CORRESPONDENCE,
    SHOW_TASK,
    HIDE_TASK
}

